name: MeshAgent Build and Push Latest

permissions:
  contents: write
  packages: write
  actions: write
  pull-requests: write
  attestations: write
  id-token: write

on:
  push:
    branches: [master, feature/agent-ci]
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g., v1.2.3)"
        required: true
        type: string

env:
  REGISTRY: "ghcr.io"
  ORGANISATION: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}

# =============================================================================
# JOBS
# =============================================================================

jobs:
  build_client:
    name: "Build C Client (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    if: |
      github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows x64"
            os: windows-latest
            os_arch: x64
            archid: 4
            artifact_name: meshagent-windows-x64.exe
          - name: "Windows x86"
            os: windows-latest
            os_arch: Win32
            archid: 3
            artifact_name: meshagent-windows-x86.exe
          - name: "macOS x86-64"
            os: macos-13
            os_arch: x86-64
            archid: 16
            artifact_name: meshagent_osx-x86-64
          - name: "macOS ARM64"
            os: macos-latest
            os_arch: arm64
            archid: 29
            artifact_name: meshagent_osx-arm-64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup MSBuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2
      
      - name: Setup Visual Studio Build Tools
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.os_arch }}      

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: brew install openssl jpeg zlib
        shell: bash
      
      - name: Build MeshAgent for Windows ${{ matrix.os_arch }} with MSBuild
        if: matrix.os == 'windows-latest'
        run: msbuild MeshAgent-2022.sln -p:Configuration=Release -p:Platform="${{ matrix.os_arch }}" -p:WindowsTargetPlatformVersion=10.0.26100.0
        shell: cmd

      - name: Build MeshAgent for macOS ${{ matrix.os_arch }}
        if: runner.os == 'macOS'
        run: |
          echo "Building MeshAgent for macOS ${{ matrix.os_arch }}"
          make macos ARCHID=${{ matrix.archid }}
        shell: bash

      - name: Prepare Artifacts
        if: runner.os == 'macOS'
        shell: bash
        run: |
          mkdir -p artifacts          
          if [[ "${{ matrix.os_arch }}" == "arm64" ]]; then
            BINARY_NAME="meshagent_osx-arm-64"
          elif [[ "${{ matrix.os_arch }}" == "x86-64" ]]; then
            BINARY_NAME="meshagent_osx-x86-64"
          fi
          cp "$BINARY_NAME" "artifacts/"

      - name: Upload client artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            artifacts/
          if-no-files-found: warn
          retention-days: 30
          compression-level: 9

      - name: Upload Windows client artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            "**/Release/*.exe"
          if-no-files-found: warn
          retention-days: 30
          compression-level: 9
