name: MeshAgent Build and Test Latest

permissions:
  contents: write
  packages: write
  actions: write
  pull-requests: write
  attestations: write
  id-token: write

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
    paths-ignore:
      - "**/*.md"

concurrency:
  group: pr-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

env:
  REGISTRY: "ghcr.io"
  ORGANISATION: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}

# =============================================================================
# JOBS
# =============================================================================

jobs:
  build_client:
    name: "Build C Client (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    if: |
      (github.event_name == 'pull_request' && !github.event.pull_request.draft)
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "macOS x86-64"
            os: macos-13
            os_arch: x86-64
            archid: 16
            artifact_name: meshagent_osx-x86-64
          - name: "macOS ARM64"
            os: macos-latest
            os_arch: arm64
            archid: 29
            artifact_name: meshagent_osx-arm-64
          - name: "Windows x64"
            os: windows-latest
            os_arch: x64
            archid: 4
            artifact_name: meshagent-windows-x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup MSBuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2
      
      - name: Setup Visual Studio Build Tools
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.os_arch }}      

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: brew install openssl jpeg zlib
        shell: bash
      
      - name: Build MeshAgent for Windows ${{ matrix.os_arch }} with MSBuild
        if: matrix.os == 'windows-latest'
        run: msbuild MeshAgent-2022.sln -p:Configuration=Release -p:Platform=${{ matrix.os_arch }} -p:WindowsTargetPlatformVersion=10.0.26100.0
        shell: cmd

      - name: Build MeshAgent for macOS ${{ matrix.os_arch }}
        if: runner.os == 'macOS'
        run: |
          echo "Building MeshAgent for macOS ${{ matrix.os_arch }}"
          make macos ARCHID=${{ matrix.archid }}
        shell: bash